# Generated by Django 5.1.15 on 2026-03-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penguin_mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='oauth_token',
        ),
        migrations.AddField(
            model_name='account',
            name='imap_host',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='imap_password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='imap_port',
            field=models.PositiveIntegerField(default=993),
        ),
        migrations.AddField(
            model_name='account',
            name='imap_security',
            field=models.CharField(default='ssl', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='smtp_host',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='smtp_password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='account',
            name='smtp_security',
            field=models.CharField(default='starttls', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(default='custom', max_length=20),
        ),
    ]
