# Generated by Django 5.1.15 on 2026-03-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penguin_mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='oauth_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='provider',
        ),
        migrations.AddField(
            model_name='account',
            name='imap_password',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='imap_url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='smtp_password',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='smtp_url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
