# Generated by Django 5.1.15 on 2026-03-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("penguin_mail", "0003_remove_account_oauth_token_account_imap_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="imap_folder",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="email",
            name="imap_uid",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
