PROVIDER_PRESETS = {
    'gmail': {
        'label': 'Gmail',
        'smtp_host': 'smtp.gmail.com',
        'smtp_port': 587,
        'smtp_security': 'starttls',
        'imap_host': 'imap.gmail.com',
        'imap_port': 993,
        'imap_security': 'ssl',
    },
    'yahoo': {
        'label': 'Yahoo',
        'smtp_host': 'smtp.mail.yahoo.com',
        'smtp_port': 465,
        'smtp_security': 'ssl',
        'imap_host': 'imap.mail.yahoo.com',
        'imap_port': 993,
        'imap_security': 'ssl',
    },
    'outlook': {
        'label': 'Outlook',
        'smtp_host': 'smtp-mail.outlook.com',
        'smtp_port': 587,
        'smtp_security': 'starttls',
        'imap_host': 'outlook.office365.com',
        'imap_port': 993,
        'imap_security': 'ssl',
    },
    'icloud': {
        'label': 'iCloud',
        'smtp_host': 'smtp.mail.me.com',
        'smtp_port': 587,
        'smtp_security': 'starttls',
        'imap_host': 'imap.mail.me.com',
        'imap_port': 993,
        'imap_security': 'ssl',
    },
    'aol': {
        'label': 'AOL',
        'smtp_host': 'smtp.aol.com',
        'smtp_port': 465,
        'smtp_security': 'ssl',
        'imap_host': 'imap.aol.com',
        'imap_port': 993,
        'imap_security': 'ssl',
    },
    'zoho': {
        'label': 'Zoho',
        'smtp_host': 'smtp.zoho.com',
        'smtp_port': 465,
        'smtp_security': 'ssl',
        'imap_host': 'imap.zoho.com',
        'imap_port': 993,
        'imap_security': 'ssl',
    },
    'fastmail': {
        'label': 'Fastmail',
        'smtp_host': 'smtp.fastmail.com',
        'smtp_port': 587,
        'smtp_security': 'starttls',
        'imap_host': 'imap.fastmail.com',
        'imap_port': 993,
        'imap_security': 'ssl',
    },
}

# Map email domains to provider keys
DOMAIN_TO_PROVIDER = {
    'gmail.com': 'gmail',
    'googlemail.com': 'gmail',
    'yahoo.com': 'yahoo',
    'yahoo.co.uk': 'yahoo',
    'yahoo.ca': 'yahoo',
    'ymail.com': 'yahoo',
    'outlook.com': 'outlook',
    'hotmail.com': 'outlook',
    'live.com': 'outlook',
    'msn.com': 'outlook',
    'icloud.com': 'icloud',
    'me.com': 'icloud',
    'mac.com': 'icloud',
    'aol.com': 'aol',
    'zoho.com': 'zoho',
    'zohomail.com': 'zoho',
    'fastmail.com': 'fastmail',
    'fastmail.fm': 'fastmail',
}
